version: '3.8'

services:
  ai-core:
    container_name: poc-ai-core
    build: ./backend/ai-core
    ports:
      - "9000:9000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OAI_TOKEN=aa
      - OAI_API_URL=http://bugatti.internal-headscale.ucaia.com:8920/v1/chat/completions
    volumes:
      - ./backend/src:/app

  log-preprocessor:
    build: ./backend/log-preprocessor
    ports:
      - "9501:9501"
    environment:
      - SERVER_PORT=9501
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=test
      - CLICKHOUSE_PASS=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=
      - REDIS_DB=0
    depends_on:
      - clickhouse
      - redis

  log-client:
    restart: no
    container_name: poc-log-client
    build: ./log-client
    volumes:
      - ./logs/dmesg/50-line.log:/logs/log.log
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - log-preprocessor
      - redis

  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_USER=test
      - CLICKHOUSE_PASSWORD=password

  redis:
    container_name: poc-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./container-data/redis/data:/data
