services:
  ai-core:
    container_name: poc-ai-core
    image: poc/ai-core:latest
    build: ./backend/ai-core
    depends_on:
      - redis
    environment:
      - REDIS_HOST=poc-redis
      - REDIS_PORT=6379
      - OLLAMA_TOKEN=aa
      - OLLAMA_API_URL=http://erikp-desktop-nix.internal-headscale.ucaia.com:11434/api/generate
      - OLLAMA_MODEL_NAME=deepseek-coder-v2

  log-preprocessor:
    container_name: poc-log-preprocessor
    image: poc/log-preprocessor:latest
    build: ./backend/log-preprocessor
    ports:
      - "9501:9501"
    environment:
      - SERVER_PORT=9501
      - CLICKHOUSE_HOST=poc-clickhouse
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASS=password
      - REDIS_HOST=poc-redis
      - REDIS_PORT=6379
      - REDIS_PASS=
      - REDIS_DB=0
    depends_on:
      - clickhouse
      - redis
    # command: tail -f /dev/null

  mock-vector-client:
    container_name: poc-mock-vector-client
    image: poc/mock-vector-client:latest
    build: ./backend/mock-vector-client
    environment:
      - HTTP_SINK_URI="http://poc-log-preprocessor:9501/test/http_sink"
    volumes:
      - ./backend/mock-vector-client/nginx-logs:/var/log/nginx
    restart: no
    depends_on:
      - log-preprocessor

  clickhouse:
    container_name: poc-clickhouse
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: password
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    container_name: poc-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  goose:
    container_name: poc-goose
    build: ./backend/goose
    depends_on:
      clickhouse:
        condition: service_healthy
    environment:
      GOOSE_DRIVER: clickhouse
      GOOSE_DBSTRING: "clickhouse://default:password@clickhouse:9000/default"
    volumes:
      - ./backend/goose/migrations:/migrations
    entrypoint: ["goose", "-dir", "/migrations", "up"]
