version: '3'

services:
  backend:
    container_name: poc-backend
    build: ./backend
    ports:
      - "9000:9000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=logparse-nix.internal-headscale.ucaia.com
      - REDIS_PORT=6379
      - TABBY_API_KEY=aa
      - TABBY_API_URL=http://bugatti.internal-headscale.ucaia.com:8920/v1/chat/completions
      - TABBY_HOST=100.64.0.14
      - TABBY_PORT=5000
    volumes:
      - ./backend/src:/app

  log-client:
    restart: no
    container_name: poc-log-client
    build: ./log-client
    volumes:
      - ./logs/dmesg/50-line.log:/logs/log.log
    depends_on:
      - backend
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    container_name: poc-redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./container-data/redis/data:/data